name: Maven Tests
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'
      
      - name: Install Angular dependencies
        run: npm install
        working-directory: ./frontend-angular
      
      - name: Build Angular
        run: npm run build
        working-directory: ./frontend-angular
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: ./backend
        continue-on-error: true
      
      - name: Build and run tests
        run: mvn clean test
        working-directory: ./backend
      
      - name: Build package
        run: mvn -B -DskipTests package
        working-directory: ./backend
      
      - name: Upload JAR artifact to root
        uses: actions/upload-artifact@v4
        with:
          name: asobo-build
          path: *.jar